// code:
// name:
package basic;

/**
 *
 * @author Pom
 */
public class Gui_4 extends javax.swing.JFrame {

    /**
     * Creates new form Gui_4
     */
    public Gui_4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        lbln1 = new javax.swing.JLabel();
        lbln2 = new javax.swing.JLabel();
        txtn1 = new javax.swing.JTextField();
        txtn2 = new javax.swing.JTextField();
        lblkq = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        lbln3 = new javax.swing.JLabel();
        lbln4 = new javax.swing.JLabel();
        txtn3 = new javax.swing.JTextField();
        txtn4 = new javax.swing.JTextField();
        lblkq1 = new javax.swing.JLabel();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("Tính Toán");
        jFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbln1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbln1.setForeground(new java.awt.Color(0, 51, 255));
        lbln1.setText("Nhập vào số thứ 1:");

        lbln2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbln2.setForeground(new java.awt.Color(0, 51, 255));
        lbln2.setText("Nhập vào số thứ 2:");

        txtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtn1.setForeground(new java.awt.Color(0, 51, 255));
        txtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtn1ActionPerformed(evt);
            }
        });

        txtn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtn2.setForeground(new java.awt.Color(0, 51, 255));

        lblkq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblkq.setForeground(new java.awt.Color(0, 51, 255));
        lblkq.setText("Kết quả:");

        bt1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt1.setForeground(new java.awt.Color(0, 51, 255));
        bt1.setText("Làm Lại");

        bt2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt2.setForeground(new java.awt.Color(0, 51, 255));
        bt2.setText("Tính Toán");

        bt3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt3.setForeground(new java.awt.Color(0, 51, 255));
        bt3.setText("Thoát");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbln1)
                            .addComponent(lbln2))
                        .addGap(53, 53, 53)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtn1)
                            .addComponent(txtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lblkq)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt1)
                .addGap(70, 70, 70)
                .addComponent(bt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbln1)
                    .addComponent(txtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbln2)
                    .addComponent(txtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lblkq)
                .addGap(39, 39, 39)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt1)
                    .addComponent(bt2)
                    .addComponent(bt3))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbln3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbln3.setForeground(new java.awt.Color(0, 51, 255));
        lbln3.setText("Nhập vào số thứ 1:");

        lbln4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbln4.setForeground(new java.awt.Color(0, 51, 255));
        lbln4.setText("Nhập vào số thứ 2:");

        txtn3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtn3.setForeground(new java.awt.Color(0, 51, 255));
        txtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtn3ActionPerformed(evt);
            }
        });

        txtn4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtn4.setForeground(new java.awt.Color(0, 51, 255));

        lblkq1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblkq1.setForeground(new java.awt.Color(0, 51, 255));
        lblkq1.setText("Kết quả:");

        bt4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt4.setForeground(new java.awt.Color(0, 51, 255));
        bt4.setText("Làm Lại");

        bt5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt5.setForeground(new java.awt.Color(0, 51, 255));
        bt5.setText("Tính Toán");

        bt6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt6.setForeground(new java.awt.Color(0, 51, 255));
        bt6.setText("Thoát");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbln3)
                            .addComponent(lbln4))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtn3)
                            .addComponent(txtn4, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lblkq1)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(bt5)
                .addGap(54, 54, 54)
                .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbln3)
                    .addComponent(txtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbln4)
                    .addComponent(txtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lblkq1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt4)
                    .addComponent(bt5)
                    .addComponent(bt6))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtn1ActionPerformed

    private void txtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel lblkq;
    private javax.swing.JLabel lblkq1;
    private javax.swing.JLabel lbln1;
    private javax.swing.JLabel lbln2;
    private javax.swing.JLabel lbln3;
    private javax.swing.JLabel lbln4;
    private javax.swing.JTextField txtn1;
    private javax.swing.JTextField txtn2;
    private javax.swing.JTextField txtn3;
    private javax.swing.JTextField txtn4;
    // End of variables declaration//GEN-END:variables
}
